name: extensions
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: 0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  lintingpackage:
      path: ../lintingpackage
