name: extensions
description: "Most common extensions for Dart and Flutter"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.3.4

dependencies:
  intl: 0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  lintingpackage:
      path: ../lintingpackage
